// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYmrDQkFD5_jzY3SQmLn8sB9PvACNW4s',
    appId: '1:54532025133:web:12b377520beffc593fc1a4',
    messagingSenderId: '54532025133',
    projectId: 'women-safety-sos-4be3b',
    authDomain: 'women-safety-sos-4be3b.firebaseapp.com',
    storageBucket: 'women-safety-sos-4be3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLuLF7phdsQ-J_SJfpZN2I4rO_1drsiFE',
    appId: '1:54532025133:android:9cb46fc6912bc9823fc1a4',
    messagingSenderId: '54532025133',
    projectId: 'women-safety-sos-4be3b',
    storageBucket: 'women-safety-sos-4be3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdfKMNjJmmEoTHNjZFiHdXCRBwxwTTc8',
    appId: '1:54532025133:ios:dbd90114b62af44e3fc1a4',
    messagingSenderId: '54532025133',
    projectId: 'women-safety-sos-4be3b',
    storageBucket: 'women-safety-sos-4be3b.appspot.com',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdfKMNjJmmEoTHNjZFiHdXCRBwxwTTc8',
    appId: '1:54532025133:ios:dbd90114b62af44e3fc1a4',
    messagingSenderId: '54532025133',
    projectId: 'women-safety-sos-4be3b',
    storageBucket: 'women-safety-sos-4be3b.appspot.com',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmYmrDQkFD5_jzY3SQmLn8sB9PvACNW4s',
    appId: '1:54532025133:web:42b622e33f7940443fc1a4',
    messagingSenderId: '54532025133',
    projectId: 'women-safety-sos-4be3b',
    authDomain: 'women-safety-sos-4be3b.firebaseapp.com',
    storageBucket: 'women-safety-sos-4be3b.appspot.com',
  );
}
